services:
    gpt-bot:
        build: .
        restart: always
        depends_on:
            - postgres
        environment:
            DATABASE_TYPE: postgresql
        volumes:
            - ./status.txt:/bot/status.txt:ro

    postgres:
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
