services:
    gpt-bot:
        build: .
        restart: always
        depends_on:
            - redis
            - postgres
        environment:
            DATABASE_TYPE: postgresql
        volumes:
            - ./database/sqlite:/app/database/sqlite

    redis:
        image: redis/redis-stack:latest
        restart: always
        ports:
            - "${REDIS_PORT}:6379"
            - "${REDIS_WEB_PORT}:8001"
        volumes:
            - "./database/redis:/data"
            - "./database/redis/redis.conf:/redis-stack.conf"

    postgres:
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - "5432:5432"
        volumes:
            - ./database/postgres:/var/lib/postgresql/data
