name: CD

on:
  push:
    branches:
      - main
    tags:
      - v*
    paths:
      - "app/**"
      - "dockerfile"
      - ".github/workflows/CD.yml"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: set lower case repository name
        run: |
          echo "REPO_LC=${REPO,,}" >> $GITHUB_ENV
        env:
          REPO: "${{ github.repository }}"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image (latest)
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/${{ env.REPO_LC }}:latest

      - name: Build and push Docker image (tagged)
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/${{ env.REPO_LC }}:${{ github.ref_name }}
